#!/usr/bin/env python3
"""Generate IconsPhosphor.h from the Phosphor web package's style.css.

Usage: gen_phosphor_icons.py <style.css> <IconsPhosphor.h>

Each `.ph.ph-<name>:before { content: "\\e3d0"; }` rule becomes
`#define ICON_PH_<NAME> "\\xEE\\x8F\\x90"` (UTF-8 encoded codepoint) plus a
`ICON_PH_CP_<NAME>` integer codepoint and a name table for the sticker picker.
Codepoints are identical across weights (regular / fill / ...).
"""
import re
import sys


RULE = re.compile(r'\.ph\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]{4})"')


def utf8_escape(cp: int) -> str:
    return "".join("\\x%02X" % b for b in chr(cp).encode("utf-8"))


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    css_path, out_path = sys.argv[1], sys.argv[2]
    with open(css_path, "r", encoding="utf-8") as f:
        css = f.read()

    icons = {}
    for name, hexcp in RULE.findall(css):
        cp = int(hexcp, 16)
        icons.setdefault(name, cp)
    if not icons:
        print("no icon rules found in", css_path, file=sys.stderr)
        return 1

    names = sorted(icons)
    lo = min(icons.values())
    hi = max(icons.values())

    lines = [
        "// IconsPhosphor.h — generated by tools/gen_phosphor_icons.py from Phosphor style.css. Do not edit.",
        "// Codepoints live in the Private Use Area; the same values are used by every weight.",
        "#pragma once",
        "",
        "#define ICON_MIN_PH 0x%04X" % lo,
        "#define ICON_MAX_PH 0x%04X" % hi,
        "#define ICON_PH_COUNT %d" % len(names),
        "",
    ]
    for name in names:
        ident = name.upper().replace("-", "_")
        cp = icons[name]
        lines.append('#define ICON_PH_%s "%s" // U+%04X ph-%s' % (ident, utf8_escape(cp), cp, name))
    lines.append("")
    lines.append("// Name table (kebab-case name, UTF-8 glyph, codepoint) for pickers/lookups.")
    lines.append("struct IconPhosphorEntry { const char* name; const char* glyph; unsigned int codepoint; };")
    lines.append("static const IconPhosphorEntry ICON_PH_NAME_TABLE[] = {")
    for name in names:
        cp = icons[name]
        lines.append('    { "%s", "%s", 0x%04X },' % (name, utf8_escape(cp), cp))
    lines.append("};")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("IconsPhosphor.h: %d icons (U+%04X..U+%04X)" % (len(names), lo, hi))
    return 0


if __name__ == "__main__":
    sys.exit(main())
