# Phosphor.cmake — generates ${CMAKE_BINARY_DIR}/generated/IconsPhosphor.h from the Phosphor
# web package's regular/style.css (codepoints are identical across weights).

find_package(Python3 COMPONENTS Interpreter QUIET)

set(EVOBOX_PHOSPHOR_CSS ${CMAKE_SOURCE_DIR}/third_party/web/src/regular/style.css)
set(EVOBOX_PHOSPHOR_HEADER ${CMAKE_BINARY_DIR}/generated/IconsPhosphor.h)
set(EVOBOX_PHOSPHOR_TOOL ${CMAKE_SOURCE_DIR}/tools/gen_phosphor_icons.py)

file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/generated)

if(NOT EXISTS ${EVOBOX_PHOSPHOR_CSS})
    message(FATAL_ERROR "Phosphor icons not found at ${EVOBOX_PHOSPHOR_CSS} (third_party/web).")
endif()

if(Python3_Interpreter_FOUND)
    add_custom_command(
        OUTPUT ${EVOBOX_PHOSPHOR_HEADER}
        COMMAND ${Python3_EXECUTABLE} ${EVOBOX_PHOSPHOR_TOOL} ${EVOBOX_PHOSPHOR_CSS} ${EVOBOX_PHOSPHOR_HEADER}
        DEPENDS ${EVOBOX_PHOSPHOR_CSS} ${EVOBOX_PHOSPHOR_TOOL}
        COMMENT "Generating IconsPhosphor.h from Phosphor style.css"
        VERBATIM)
else()
    # No Python: generate once at configure time with CMake's regex engine (slower, but works).
    message(STATUS "Python3 not found; generating IconsPhosphor.h with CMake")
    file(READ ${EVOBOX_PHOSPHOR_CSS} _css)
    string(REGEX MATCHALL "\\.ph\\.ph-([a-z0-9-]+):before[ \t\r\n]*{[ \t\r\n]*content:[ \t]*\"\\\\([0-9a-f]+)\"" _matches "${_css}")
    set(_out "// Generated by cmake/Phosphor.cmake — do not edit.\n#pragma once\n#define ICON_MIN_PH 0xE000\n#define ICON_MAX_PH 0xEE83\n")
    foreach(_m IN LISTS _matches)
        string(REGEX REPLACE "\\.ph\\.ph-([a-z0-9-]+):before.*" "\\1" _name "${_m}")
        string(REGEX REPLACE ".*content:[ \t]*\"\\\\([0-9a-f]+)\".*" "\\1" _hex "${_m}")
        string(TOUPPER "${_name}" _upper)
        string(REPLACE "-" "_" _upper "${_upper}")
        math(EXPR _cp "0x${_hex}")
        math(EXPR _b0 "0xE0 | (${_cp} >> 12)")
        math(EXPR _b1 "0x80 | ((${_cp} >> 6) & 0x3F)")
        math(EXPR _b2 "0x80 | (${_cp} & 0x3F)")
        math(EXPR _b0 "${_b0}" OUTPUT_FORMAT HEXADECIMAL)
        math(EXPR _b1 "${_b1}" OUTPUT_FORMAT HEXADECIMAL)
        math(EXPR _b2 "${_b2}" OUTPUT_FORMAT HEXADECIMAL)
        string(REPLACE "0x" "\\x" _b0 "${_b0}")
        string(REPLACE "0x" "\\x" _b1 "${_b1}")
        string(REPLACE "0x" "\\x" _b2 "${_b2}")
        string(APPEND _out "#define ICON_PH_${_upper} \"${_b0}${_b1}${_b2}\" // U+${_hex}\n")
    endforeach()
    file(WRITE ${EVOBOX_PHOSPHOR_HEADER} "${_out}")
endif()

add_custom_target(evobox_phosphor_header DEPENDS ${EVOBOX_PHOSPHOR_HEADER})
